puts 'Creating memory...'
puts 'Creating signs...'
signs_array = ["Aries", "Taurus", "Gemini", "Cancer", "Leo", "Virgo", "Libra", "Scorpio", "Sagittarius", "Capricorn", "Aquarius", "Pisces"]

signs_array.each do |sign|
  Sign.find_or_create_by!(sign_name: sign)
end
puts 'Signs created!'

puts "Create Brazilian states"

states_array = ["Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins"]
states_array.each do |state_br|
  State.find_or_create_by!(state_name: state_br)
end

puts "Brazilian states created"

puts 'Creating matches!'
SignMatch.find_or_create_by!(sign_one_id: 1,  sign_two_id: 1, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 1,  sign_two_id: 2, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 1,  sign_two_id: 3, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 1,  sign_two_id: 4, percentage: 65)
SignMatch.find_or_create_by!(sign_one_id: 1,  sign_two_id: 5, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 1,  sign_two_id: 6, percentage: 45)
SignMatch.find_or_create_by!(sign_one_id: 1,  sign_two_id: 7, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 1,  sign_two_id: 8, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 1,  sign_two_id: 9, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 1,  sign_two_id: 10, percentage: 50)
SignMatch.find_or_create_by!(sign_one_id: 1,  sign_two_id: 11, percentage: 55)
SignMatch.find_or_create_by!(sign_one_id: 1,  sign_two_id: 12, percentage: 65)
SignMatch.find_or_create_by!(sign_one_id: 2,  sign_two_id: 1, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 2,  sign_two_id: 2, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 2,  sign_two_id: 3, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 2,  sign_two_id: 4, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 2,  sign_two_id: 5, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 2,  sign_two_id: 6, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 2,  sign_two_id: 7, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 2,  sign_two_id: 8, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 2,  sign_two_id: 9, percentage: 50)
SignMatch.find_or_create_by!(sign_one_id: 2,  sign_two_id: 10, percentage: 95)
SignMatch.find_or_create_by!(sign_one_id: 2,  sign_two_id: 11, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 2,  sign_two_id: 12, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 3,  sign_two_id: 1, percentage: 65)
SignMatch.find_or_create_by!(sign_one_id: 3,  sign_two_id: 2, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 3,  sign_two_id: 3, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 3,  sign_two_id: 4, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 3,  sign_two_id: 5, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 3,  sign_two_id: 6, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 3,  sign_two_id: 7, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 3,  sign_two_id: 8, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 3,  sign_two_id: 9, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 3,  sign_two_id: 10, percentage: 50)
SignMatch.find_or_create_by!(sign_one_id: 3,  sign_two_id: 11, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 3,  sign_two_id: 12, percentage: 50)
SignMatch.find_or_create_by!(sign_one_id: 4,  sign_two_id: 1, percentage: 65)
SignMatch.find_or_create_by!(sign_one_id: 4,  sign_two_id: 2, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 4,  sign_two_id: 3, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 4,  sign_two_id: 4, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 4,  sign_two_id: 5, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 4,  sign_two_id: 6, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 4,  sign_two_id: 7, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 4,  sign_two_id: 8, percentage: 95)
SignMatch.find_or_create_by!(sign_one_id: 4,  sign_two_id: 9, percentage: 55)
SignMatch.find_or_create_by!(sign_one_id: 4,  sign_two_id: 10, percentage: 45)
SignMatch.find_or_create_by!(sign_one_id: 4,  sign_two_id: 11, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 4,  sign_two_id: 12, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 5,  sign_two_id: 1, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 5,  sign_two_id: 2, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 5,  sign_two_id: 3, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 5,  sign_two_id: 4, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 5,  sign_two_id: 5, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 5,  sign_two_id: 6, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 5,  sign_two_id: 7, percentage: 65)
SignMatch.find_or_create_by!(sign_one_id: 5,  sign_two_id: 8, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 5,  sign_two_id: 9, percentage: 95)
SignMatch.find_or_create_by!(sign_one_id: 5,  sign_two_id: 10, percentage: 45)
SignMatch.find_or_create_by!(sign_one_id: 5,  sign_two_id: 11, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 5,  sign_two_id: 12, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 6,  sign_two_id: 1, percentage: 45)
SignMatch.find_or_create_by!(sign_one_id: 6,  sign_two_id: 2, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 6,  sign_two_id: 3, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 6,  sign_two_id: 4, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 6,  sign_two_id: 5, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 6,  sign_two_id: 6, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 6,  sign_two_id: 7, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 6,  sign_two_id: 8, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 6,  sign_two_id: 9, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 6,  sign_two_id: 10, percentage: 95)
SignMatch.find_or_create_by!(sign_one_id: 6,  sign_two_id: 11, percentage: 50)
SignMatch.find_or_create_by!(sign_one_id: 6,  sign_two_id: 12, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 7,  sign_two_id: 1, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 7,  sign_two_id: 2, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 7,  sign_two_id: 3, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 7,  sign_two_id: 4, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 7,  sign_two_id: 5, percentage: 65)
SignMatch.find_or_create_by!(sign_one_id: 7,  sign_two_id: 6, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 7,  sign_two_id: 7, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 7,  sign_two_id: 8, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 7,  sign_two_id: 9, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 7,  sign_two_id: 10, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 7,  sign_two_id: 11, percentage: 95)
SignMatch.find_or_create_by!(sign_one_id: 7,  sign_two_id: 12, percentage: 50)
SignMatch.find_or_create_by!(sign_one_id: 8,  sign_two_id: 1, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 8,  sign_two_id: 2, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 8,  sign_two_id: 3, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 8,  sign_two_id: 4, percentage: 95)
SignMatch.find_or_create_by!(sign_one_id: 8,  sign_two_id: 5, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 8,  sign_two_id: 6, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 8,  sign_two_id: 7, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 8,  sign_two_id: 8, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 8,  sign_two_id: 9, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 8,  sign_two_id: 10, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 8,  sign_two_id: 11, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 8,  sign_two_id: 12, percentage: 95)
SignMatch.find_or_create_by!(sign_one_id: 9,  sign_two_id: 1, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 9,  sign_two_id: 2, percentage: 50)
SignMatch.find_or_create_by!(sign_one_id: 9,  sign_two_id: 3, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 9,  sign_two_id: 4, percentage: 55)
SignMatch.find_or_create_by!(sign_one_id: 9,  sign_two_id: 5, percentage: 95)
SignMatch.find_or_create_by!(sign_one_id: 9,  sign_two_id: 6, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 9,  sign_two_id: 7, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 9,  sign_two_id: 8, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 9,  sign_two_id: 9, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 9,  sign_two_id: 10, percentage: 55)
SignMatch.find_or_create_by!(sign_one_id: 9,  sign_two_id: 11, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 9,  sign_two_id: 12, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 10, sign_two_id: 1, percentage: 50)
SignMatch.find_or_create_by!(sign_one_id: 10, sign_two_id: 2, percentage: 95)
SignMatch.find_or_create_by!(sign_one_id: 10, sign_two_id: 3, percentage: 50)
SignMatch.find_or_create_by!(sign_one_id: 10, sign_two_id: 4, percentage: 45)
SignMatch.find_or_create_by!(sign_one_id: 10, sign_two_id: 5, percentage: 45)
SignMatch.find_or_create_by!(sign_one_id: 10, sign_two_id: 6, percentage: 95)
SignMatch.find_or_create_by!(sign_one_id: 10, sign_two_id: 7, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 10, sign_two_id: 8, percentage: 65)
SignMatch.find_or_create_by!(sign_one_id: 10, sign_two_id: 9, percentage: 55)
SignMatch.find_or_create_by!(sign_one_id: 10, sign_two_id: 10, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 10, sign_two_id: 11, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 10, sign_two_id: 12, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 11, sign_two_id: 1, percentage: 55)
SignMatch.find_or_create_by!(sign_one_id: 11, sign_two_id: 2, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 11, sign_two_id: 3, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 11, sign_two_id: 4, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 11, sign_two_id: 5, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 11, sign_two_id: 6, percentage: 50)
SignMatch.find_or_create_by!(sign_one_id: 11, sign_two_id: 7, percentage: 95)
SignMatch.find_or_create_by!(sign_one_id: 11, sign_two_id: 8, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 11, sign_two_id: 9, percentage: 60)
SignMatch.find_or_create_by!(sign_one_id: 11, sign_two_id: 10, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 11, sign_two_id: 11, percentage: 80)
SignMatch.find_or_create_by!(sign_one_id: 11, sign_two_id: 12, percentage: 55)
SignMatch.find_or_create_by!(sign_one_id: 12, sign_two_id: 1, percentage: 65)
SignMatch.find_or_create_by!(sign_one_id: 12, sign_two_id: 2, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 12, sign_two_id: 3, percentage: 50)
SignMatch.find_or_create_by!(sign_one_id: 12, sign_two_id: 4, percentage: 90)
SignMatch.find_or_create_by!(sign_one_id: 12, sign_two_id: 5, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 12, sign_two_id: 6, percentage: 70)
SignMatch.find_or_create_by!(sign_one_id: 12, sign_two_id: 7, percentage: 50)
SignMatch.find_or_create_by!(sign_one_id: 12, sign_two_id: 8, percentage: 95)
SignMatch.find_or_create_by!(sign_one_id: 12, sign_two_id: 9, percentage: 75)
SignMatch.find_or_create_by!(sign_one_id: 12, sign_two_id: 10, percentage: 85)
SignMatch.find_or_create_by!(sign_one_id: 12, sign_two_id: 11, percentage: 55)
SignMatch.find_or_create_by!(sign_one_id: 12, sign_two_id: 12, percentage: 80)
puts 'Matches created!'
puts 'Memory created!'
